---
- name: Apply Patch | Copy the patch file to /tmp/{{ patch_file | basename }}
  copy:
    src: "{{ pkg_location | default('files') }}/{{ patch_file }}"
    dest: "/tmp/"
    mode: 0644

- name: Apply Patch | Determine if patch can be applied
  command: "{{ home_directory }}/bin/jboss-cli.sh 'patch info'"
  become: yes
  become_user: "{{ system_user }}"
  register: patch_info
  changed_when: no

- name: Apply Patch | Apply JBoss EAP patch
  command: "{{ home_directory }}/bin/jboss-cli.sh 'patch apply /tmp/{{ patch_file | basename }}'"
  become: yes
  become_user: "{{ system_user }}"
  when:
    - "'base' in jboss_patch_info.stdout"
  notify: restart service

- name: cleanup
  file:
    path: "/tmp/{{ patch_file }}"
    state: absent
