---
- name: Configure Domain | Copy Domain XML template to Master
  template:
    src: templates/{{ install }}.domain.xml
    dest: "{{ home_directory }}/{{ server_mode }}/configuration/domain.xml"
    force: true
  when: "inventory_hostname in master_server"
  notify:
    - start service

- name: Configure Domain | Copy Slaves XML template to all Slaves
  template:
    src: templates/{{ install }}.host-slave.xml
    dest: "{{ home_directory }}/{{ server_mode }}/configuration/host-slave.xml"
    force: true
  when: "inventory_hostname not in master_server"
  notify:
    - start service

- name: Configure Domain | Add JDBC module configuration
  copy:
    src: files/modules/{{ item.location }}/{{ item.name }}
    dest: "{{ home_directory }}/modules/{{ item.location }}"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: '0644'
  when: "inventory_hostname not in lb_server"
  loop: "{{ jdbc_modules }}"
  notify:
    - start service

- name: Configure Domain | Run all staged handlers
  meta: flush_handlers
