---
# handlers file for wildfly

# Reload Systemd Configs
- name: reload systemd
  systemd:
    daemon_reload: yes

# Start Wildfly / JBoss EAP
- name: start service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes

# Restart Wildfly / JBoss EAP
- name: restart service
  systemd:
    name: "{{ service_name }}"
    state: restarted

# Start firewalld
- name: start firewall
  systemd:
    name: firewalld
    state: started
    enabled: yes

# Restart firewalld
- name: restart firewall
  systemd:
    name: firewalld
    state: restarted
